name: 1.0$(rev:.r)

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/*

pool:
  name: Azure Pipelines
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  verbosity: 'Normal'

stages:
- stage: test
  jobs:
  - job: test
    displayName: 'Tests'

    steps:

    - task: UseDotNet@2
      displayName: 'Use .NET Core 6 sdk'
      inputs:
        packageType: sdk
        version: '6.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - checkout: self
      fetchDepth: 1

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: build
        projects: 'src/**/*.csproj'
        arguments: '--configuration $(BuildConfiguration) --verbosity $(verbosity)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: |
          **/Serilog.Sinks.XUnit.Injectable.Tests.csproj
        arguments: '--configuration $(BuildConfiguration) -v n'
      displayName: 'Run tests'

    - task: BuildQualityChecks@8
      inputs:
        checkWarnings: true
        warningFailOption: 'fixed'
        warningThreshold: '0'
        showStatistics: true


- stage: deploy
  dependsOn: test
  jobs:
  - job: deploy
    steps:

    - task: DotNetCoreCLI@2
      displayName: 'Create NuGet Packages'
      inputs:
        command: 'pack'
        packagesToPack: 'src/**/*.csproj'
        versioningScheme: 'byBuildNumber'