name: 1.0$(rev:.r)

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/*
    - test/*
    - pipeline/*

pool:
  name: Azure Pipelines
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  verbosity: 'Normal'

stages:
- stage: build
  jobs:
  - job: build
    displayName: 'Build and Deploy'

    steps:

    - task: UseDotNet@2
      displayName: 'Use .NET Core 6 sdk'
      inputs:
        packageType: sdk
        version: '6.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - checkout: self
      fetchDepth: 1

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: build
        projects: 'src/**/*.csproj'
        arguments: '--configuration $(BuildConfiguration) --verbosity $(verbosity)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: |
          **/Serilog.Sinks.XUnit.Injectable.Tests.csproj
        arguments: '--configuration $(BuildConfiguration) --verbosity $(verbosity)'
      displayName: 'Run tests'

    - task: BuildQualityChecks@8
      inputs:
        checkWarnings: true
        warningFailOption: 'fixed'
        warningThreshold: '0'
        showStatistics: true

    - task: DotNetCoreCLI@2
      displayName: 'Create NuGet Package'
      inputs:
        command: 'pack'
        packagesToPack: 'src/**/*.csproj'
        versioningScheme: 'byBuildNumber'
        verbosityPack: $(verbosity)

    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'NuGet'
        verbosityPush: $(verbosity)

