name: Build and Test
on:
  # Testing - run for any PRs.
  pull_request:
    branches:
      - main

jobs:

  # Build, test and publish (if this is a push/merge).
  build-and-test:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Pack
        run: dotnet pack --no-build --configuration Release --output .
