name: Re-enable automerge
on:
  pull_request:
    branches: [main]
    types:
      - auto_merge_disabled

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    if: "github.event.reason == 'Base branch was modified'"
    runs-on: ubuntu-latest
    steps:
    - name: Debug
      run: echo "repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/update-branch"
      shell: bash

    - name: Update pull request branch
      run: gh api -X PUT "repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/update-branch"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GENERAL }}

    # This prevents pull request from being merged before running a new workflow.
    - name: wait for starting a new workflow by updating branch
      run: sleep 10
      shell: bash

    - name: enable automerge
      run: gh pr merge --auto --merge "$PR_URL"
      shell: bash
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{ secrets.GENERAL }}
